name: Build and Package Backend app
on:
  push:
    branches:
      - main
    paths:
      - "spring-boot-data-jpa-mysql-master/**"
      - ".github/workflows/backend-workflow.yml"
      - "!README.md"
      - "!spring-boot-data-jpa-mysql-master/README.md"

jobs:
  test-extract-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from commit message
        id: extract-version
        run: echo "version==$(echo ${{ github.event.head_commit.message }} | grep -oP 'tag:[^\s]+' | cut -d':' -f2)" >> $GITHUB_OUTPUT
      - name: use tag
        run: echo ${{ steps.extract-version.outputs.version }}
