name: Build and Package Backend app
on:
  push:
    branches:
      - main
    paths:
      - "spring-boot-data-jpa-mysql-master/**"
      - ".github/workflows/backend-workflow.yml"
      - "!README.md"
      - "!spring-boot-data-jpa-mysql-master/README.md"
jobs:
  test-extract-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from commit message
        id: extract-version
        run: |
          version=$(echo ${{ github.event.head_commit.message }} | grep -oP 'tag:[^\s]+' | cut -d':' -f2)
          if [ -z "$version" ]; then
            echo "version=latest" >> $GITHUB_OUTPUT
          else
            echo "version=$version" >> $GITHUB_OUTPUT
          fi
      - name: use tag
        run: echo ${{ steps.extract-version.outputs.version }}
