name: Build and Package Backend app
on:
  push:
    branches:
      - main
    paths:
      - "spring-boot-data-jpa-mysql-master/**"
      - ".github/workflows/backend-build-job.yml"
jobs:
  maven-build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2.0
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3308:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: cd spring-boot-data-jpa-mysql-master && mvn -B package
      - name: Archive JAR file
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: spring-boot-data-jpa-mysql-master/target/*.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download JAR file
        uses: actions/download-artifact@v3
        with:
          name: app
          path: spring-boot-data-jpa-mysql-master/target
      - name: Download JAR file
        run: ls spring-boot-data-jpa-mysql-master/target
      - name: Build Docker image
        run: cd spring-boot-data-jpa-mysql-master && docker build -t elmazidi/myapp-backend:latest .
      - name: Log in to Docker Hub
        run: docker login -u elmazidi -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend Docker image
        run: docker push elmazidi/myapp-backend:latest
