name:  Build and Package Frontend App 
on:
  push:
    branches: [ "main" ]
    paths:
      - 'angular-16-crud-example-master/**'
      - '.github/workflows/frontend-workflow.yml'
      - '!README.md' 
      - '!angular-16-crud-example-master/README.md'
jobs:
  node-build:
    if: "contains(github.event.head_commit.message,'run workflow')"
    uses: ./.github/workflows/angular-build.yaml
    with:
       directory: angular-16-crud-example-master
       artifact-name: dist
  docker-build:
    runs-on: ubuntu-latest
    needs: node-build 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Download dist folder
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: angular-16-crud-example-master/dist
    - name: Build Docker image
      run: cd angular-16-crud-example-master && docker build -t elmazidi/myapp-frontend:latest .
    - name: Log in to Docker Hub
      run: docker login -u elmazidi -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push frontend Docker image
      run: docker push elmazidi/myapp-frontend:latest
