name: Testing
on:
  push:
    branches:
      - main
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract
        uses: ./actions/image-version-action
      - name: Log
        run: echo ${{ steps.extract-version.outputs.version }}
   
